default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_form_app


test:
  <<: *default
  database: shop_form_app

#
production:
  <<: *default
  database: shop_form_app_production
  username: shop_form_app
  password: <%= ENV['shop_form_APP_DATABASE_PASSWORD'] %>
